extends Node

signal locale_changed(locale: String)

const HebrewContent := preload("res://scripts/services/localized_content_he.gd")

const STRINGS := {
	"en": {
		"tagline": "Fight giants outside. Destroy them within.",
		"story_descent": "STORY DESCENT",
		"begin_dive": "BEGIN THE DIVE",
		"last_nest": "THE LAST NEST",
		"hangar": "HANGAR",
		"forge": "FORGE",
		"research": "RESEARCH VAT",
		"rift": "RIFT TERMINAL",
		"trophies": "TROPHY CHAMBER",
		"core": "CORE CHAMBER",
		"settings": "SETTINGS",
		"bio": "BIO-MATTER",
		"shards": "CORE SHARDS",
		"difficulty": "DIFFICULTY",
		"diver": "DIVER",
		"deep": "DEEP",
		"abyss": "ABYSS",
		"locked": "LOCKED",
		"close": "CLOSE",
		"daily": "DAILY RIFT",
		"friend": "FRIEND RIFT",
		"abyss_loop": "ABYSS LOOP",
		"paste_code": "Paste a Friend Rift code",
		"open_rift": "OPEN RIFT",
		"reset_progress": "RESET PROGRESS",
		"language": "LANGUAGE",
		"english": "ENGLISH",
		"hebrew": "HEBREW",
		"assist": "ASSIST & ACCESSIBILITY",
		"controls": "CONTROLS",
		"audio": "AUDIO",
		"master_volume": "Master volume",
		"music_volume": "Music volume",
		"sfx_volume": "Sound effects",
		"haptics": "Haptics",
		"screen_shake": "Screen shake",
		"reduced_motion": "Reduced motion",
		"projectile_contrast": "High-contrast projectiles",
		"damage_flash": "Damage flash",
		"control_sensitivity": "Control sensitivity",
		"aim_assist": "Aim assistance",
		"assist_mode": "ASSIST MODE",
		"assist_projectile_speed": "Enemy projectile speed",
		"assist_telegraph": "Telegraph duration",
		"assist_dash_window": "Phase window",
		"dash_method": "Dash method",
		"handedness": "Hand preference",
		"analytics_opt_in": "Share anonymous gameplay analytics",
		"dash_button": "Dedicated dash button",
		"dash_double_tap": "Double tap",
		"dash_flick": "Quick flick",
		"hand_right": "Right-hand layout",
		"hand_left": "Left-hand layout",
		"nest_stage_0": "BROKEN SHELL",
		"nest_stage_1": "AWAKENED REACTOR",
		"nest_stage_2": "LIVING WORKSHOP",
		"nest_stage_3": "DIVER COLONY",
		"nest_stage_4": "INFINITE NEST",
		"offline_footer": "v{version} · OFFLINE CORE · NO ACCOUNT REQUIRED",
		"hangar_subtitle": "Five weapons. Five different reasons to move dangerously.",
		"equipped": "EQUIPPED",
		"select": "SELECT",
		"unlock_shards": "UNLOCK · {count} SHARDS",
		"forge_subtitle": "Permanent upgrades change every future dive and physically restore the Nest.",
		"maximum": "MAXIMUM",
		"upgrade_requires": "REQUIRES {name} · LEVEL {level}",
		"tutorial_replay": "REPLAY TUTORIAL ON NEXT RUN",
		"tutorial.drag_to_move": "DRAG TO MOVE",
		"tutorial.auto_fire": "YOUR WEAPON FIRES AUTOMATICALLY",
		"tutorial.avoid_or_dash": "AVOID THE TELEGRAPH — OR PHASE THROUGH",
		"tutorial.hit_exposed_armor": "KEEP FIRE ON THE EXPOSED ARMOR",
		"tutorial.enter_breach": "TAP DIVE NOW AND ENTER THE BREACH",
		"tutorial.destroy_organ": "DESTROY THE ORGAN POWERING THE ATTACK",
		"tutorial.choose_mutation": "CHOOSE ONE MUTATION FOR THIS RUN",
		"tutorial.observe_boss_change": "THAT ORGAN IS GONE — THE BOSS HAS CHANGED",
		"tutorial.finish_phase_or_die": "FINISH THE PHASE — OR RETURN STRONGER",
		"tutorial.spend_first_resource": "SPEND BIO-MATTER IN THE FORGE",
		"cost_bio": "{count} BIO",
		"research_subtitle": "The anatomy archive records every system you have entered.",
		"rift_subtitle": "Deterministic challenges work offline. Online leaderboards can connect later without blocking play.",
		"seed_value": "SEED {value}",
		"create_friend_rift": "CREATE FRIEND RIFT FROM CURRENT LOADOUT",
		"friend_code_copied": "Challenge code copied to the clipboard.",
		"daily_reset": "RESETS 00:00 UTC",
		"trophies_subtitle": "Every collapsed colossus leaves a permanent scar on the Nest.",
		"core_subtitle": "The deepest system of the Nest answers only after the Null Twin falls.",
		"settings_subtitle": "Assist settings preserve the full game. Competitive Daily Rifts use a fixed standard profile.",
		"support_feedback": "SUPPORT & FEEDBACK",
		"privacy_policy": "PRIVACY POLICY",
		"bio_short_value": "BIO {value}",
		"phase_dash": "PHASE\nDASH",
		"phase_ready": "PHASE\nREADY",
		"phase_charge": "PHASE\n{percent}%",
		"dive_locked": "DIVE\nLOCKED",
		"dive_now": "DIVE\nNOW",
		"organ_order_eyebrow": "THE ORDER CHANGES THE FIGHT",
		"organ_choice_title": "Which system dies first?",
		"organ_choice_body": "Every organ powers one exterior attack. Choose the threat that matters to your build.",
		"organ_fallback": "ORGAN",
		"mutation_eyebrow": "THE BOSS CHANGED. SO DO YOU.",
		"mutation_choice_title": "Choose a mutation",
		"mutation_fallback": "MUTATION",
		"reroll_left": "REROLL · {count} LEFT",
		"colossus_collapsed": "COLOSSUS COLLAPSED",
		"diver_lost": "DIVER LOST",
		"victory": "VICTORY",
		"nest_remembers": "THE NEST REMEMBERS",
		"victory_body": "The fallen colossus becomes fuel for the Nest.",
		"killed_by": "Killed by: {cause}",
		"unknown_attack": "unknown attack",
		"result_details": "TIME {time}    ORGANS {organs}/3    BANK +{bio}",
		"score_value": "SCORE {value}",
		"result_loadout": "{boss} · {weapon}",
		"result_organs_destroyed": "DESTROYED: {value}",
		"result_mutations": "MUTATIONS: {value}",
		"result_metrics": "TIME {time} · DEPTH {depth} · BANK +{bio}",
		"friend_target_beaten": "FRIEND TARGET BEAT",
		"friend_target_missed": "FRIEND TARGET NOT YET BEAT",
		"more_count": "+{count} MORE",
		"none": "NONE",
		"dive_again": "DIVE AGAIN",
		"share_rift": "SHARE RIFT",
		"return_to_nest": "RETURN TO NEST",
		"dive_paused": "DIVE PAUSED",
		"pause_body": "Combat is frozen safely.",
		"resume": "RESUME",
		"abandon_to_nest": "ABANDON TO NEST",
		"state_intro": "APPROACHING COLOSSUS",
		"state_exterior": "OUTER SHELL · BREAK THE ARMOR",
		"state_breach_open": "BREACH OPEN · DIVE NOW",
		"breach_timer": "BREACH CLOSES IN {seconds}s",
		"breach_lost": "BREACH SEALED — BREAK THE SCAR AGAIN",
		"state_organ_select": "SELECT AN ORGAN",
		"state_diving_in": "FOLDING THROUGH THE WOUND",
		"state_internal_rooms": "INSIDE · REACH THE ORGAN",
		"state_organ_chamber": "ORGAN CHAMBER · DESTROY IT",
		"state_mutation_choice": "CHOOSE A MUTATION",
		"state_diving_out": "THE OUTSIDE IS REWRITING",
		"state_core": "FINAL CORE · END THE GIANT",
		"state_dead": "DIVER LOST",
		"state_victory": "COLOSSUS COLLAPSED",
		"state_fallback": "DIVE",
		"tutorial_move": "DRAG TO MOVE · YOUR WEAPON FIRES AUTOMATICALLY",
		"colossus_fallback": "COLOSSUS",
		"internal_depth": "INTERNAL DEPTH",
		"keep_moving": "KEEP MOVING",
		"destroy_organ": "DESTROY {organ}",
		"the_organ": "THE ORGAN",
		"breach_enter": "BREACH OPEN — ENTER THE GIANT",
		"all_systems_dead": "ALL SYSTEMS DEAD — COLLAPSE THE CORE",
		"ability_disabled": "{ability} DISABLED",
		"friend_rift_copied_short": "FRIEND RIFT COPIED · {code}",
		"room_traversal": "TRAVERSAL",
		"room_combat": "COMBAT",
		"room_hazard": "HAZARD",
		"organ_scan": "SCAN · {hp} tissue · {hazard}",
		"synergy": "◆ SYNERGY",
		"synergy_detail": "◆ SYNERGY · {tag}",
		"rare": "RARE",
		"meta_reward": "GOAL COMPLETE · +{bio} BIO · +{shards} SHARDS",
		"daily_contracts": "DAILY CONTRACTS",
		"achievements": "ACHIEVEMENTS",
		"completed": "COMPLETE",
		"goal_progress": "{value}/{target}",
		"reset_warning": "This permanently removes currencies, unlocks, records, achievements and tutorial progress from this device.",
		"reset_confirm": "PERMANENTLY RESET",
		"cancel": "CANCEL",
		"room_chamber": "CHAMBER",
		"room_entrance": "ENTRANCE",
		"room_room": "ROOM",
		"internal_defender": "Internal Defender",
		"rupture_volley": "Rupture Volley",
		"hostile_projectile": "Hostile Projectile",
		"core_collapse": "Core Collapse",
		"ability_homing_eye": "Homing Eye",
		"ability_gravity_ring": "Gravity Ring",
		"ability_bone_missiles": "Bone Missiles",
		"ability_prism_lances": "Prism Lances",
		"ability_laser_wings": "Laser Wings",
		"ability_halo_barrier": "Halo Barrier",
		"ability_suction_waves": "Suction Waves",
		"ability_chain_lightning": "Chain Lightning",
		"ability_parasite_swarm": "Parasite Swarm",
		"ability_weapon_copy": "Weapon Copy",
		"ability_echo_dash": "Echo Dash",
		"ability_false_weakpoints": "False Weak Points"
	},
	"he": {
		"tagline": "נלחמים בענקים מבחוץ. משמידים אותם מבפנים.",
		"story_descent": "צלילת הסיפור",
		"begin_dive": "התחל צלילה",
		"last_nest": "הקן האחרון",
		"hangar": "האנגר",
		"forge": "הכור",
		"research": "מכל המחקר",
		"rift": "מסוף הקרעים",
		"trophies": "חדר הגביעים",
		"core": "ליבת הקן",
		"settings": "הגדרות",
		"bio": "חומר ביולוגי",
		"shards": "רסיסי ליבה",
		"difficulty": "רמת קושי",
		"diver": "צולל",
		"deep": "עמוק",
		"abyss": "תהום",
		"locked": "נעול",
		"close": "סגור",
		"daily": "קרע יומי",
		"friend": "קרע חברים",
		"abyss_loop": "לולאת התהום",
		"paste_code": "הדבק קוד של קרע חברים",
		"open_rift": "פתח קרע",
		"reset_progress": "אפס התקדמות",
		"language": "שפה",
		"english": "אנגלית",
		"hebrew": "עברית",
		"assist": "סיוע ונגישות",
		"controls": "שליטה",
		"audio": "שמע",
		"master_volume": "עוצמת שמע ראשית",
		"music_volume": "עוצמת מוזיקה",
		"sfx_volume": "אפקטים קוליים",
		"haptics": "רטט",
		"screen_shake": "רעידות מסך",
		"reduced_motion": "הפחתת תנועה",
		"projectile_contrast": "קליעים בניגודיות גבוהה",
		"damage_flash": "הבזק נזק",
		"control_sensitivity": "רגישות שליטה",
		"aim_assist": "סיוע בכיוון",
		"assist_mode": "מצב סיוע",
		"assist_projectile_speed": "מהירות קליעי אויב",
		"assist_telegraph": "משך טלגרף",
		"assist_dash_window": "חלון פאזה",
		"dash_method": "שיטת זינוק",
		"handedness": "יד מועדפת",
		"analytics_opt_in": "שיתוף נתוני משחק אנונימיים",
		"dash_button": "כפתור זינוק ייעודי",
		"dash_double_tap": "הקשה כפולה",
		"dash_flick": "החלקה מהירה",
		"hand_right": "פריסה ליד ימין",
		"hand_left": "פריסה ליד שמאל",
		"nest_stage_0": "קליפה שבורה",
		"nest_stage_1": "כור שהתעורר",
		"nest_stage_2": "סדנה חיה",
		"nest_stage_3": "מושבת צוללים",
		"nest_stage_4": "הקן האינסופי",
		"offline_footer": "גרסה {version} · ליבה לא מקוונת · ללא צורך בחשבון",
		"hangar_subtitle": "חמישה כלי נשק. חמש סיבות שונות לנוע על הקצה.",
		"equipped": "מצויד",
		"select": "בחירה",
		"unlock_shards": "פתיחה · {count} רסיסים",
		"forge_subtitle": "שדרוגים קבועים משנים כל צלילה עתידית ומשקמים את הקן לעיני השחקן.",
		"maximum": "מקסימום",
		"upgrade_requires": "דורש {name} · רמה {level}",
		"tutorial_replay": "הפעלת ההדרכה מחדש בריצה הבאה",
		"tutorial.drag_to_move": "גררו כדי לזוז",
		"tutorial.auto_fire": "הנשק יורה אוטומטית",
		"tutorial.avoid_or_dash": "התחמקו מהטלגרף — או עברו דרכו בפאזה",
		"tutorial.hit_exposed_armor": "המשיכו לירות בשריון החשוף",
		"tutorial.enter_breach": "לחצו לצלילה והיכנסו לפרצה",
		"tutorial.destroy_organ": "השמידו את האיבר שמפעיל את המתקפה",
		"tutorial.choose_mutation": "בחרו מוטציה אחת לריצה הזו",
		"tutorial.observe_boss_change": "האיבר הושמד — הבוס השתנה",
		"tutorial.finish_phase_or_die": "סיימו את השלב — או חזרו חזקים יותר",
		"tutorial.spend_first_resource": "הוציאו חומר ביולוגי בכבשן",
		"cost_bio": "{count} חומר ביולוגי",
		"research_subtitle": "ארכיון האנטומיה מתעד כל מערכת שאליה צללת.",
		"rift_subtitle": "אתגרים דטרמיניסטיים פועלים גם בלי רשת. טבלאות מובילים יוכלו להתחבר בהמשך בלי לחסום משחק.",
		"seed_value": "זרע {value}",
		"create_friend_rift": "יצירת קרע חברים מהציוד הנוכחי",
		"friend_code_copied": "קוד האתגר הועתק ללוח.",
		"daily_reset": "מתאפס ב־00:00 UTC",
		"trophies_subtitle": "כל ענק שקרס משאיר צלקת קבועה בקן.",
		"core_subtitle": "המערכת העמוקה ביותר בקן נענית רק לאחר נפילת תאום האפס.",
		"settings_subtitle": "הגדרות הסיוע שומרות על המשחק המלא. בקרעים יומיים תחרותיים נעשה שימוש בפרופיל אחיד.",
		"support_feedback": "תמיכה ומשוב",
		"privacy_policy": "מדיניות פרטיות",
		"bio_short_value": "חומר {value}",
		"phase_dash": "זינוק\nפאזה",
		"phase_ready": "פאזה\nמוכנה",
		"phase_charge": "פאזה\n{percent}%",
		"dive_locked": "צלילה\nנעולה",
		"dive_now": "צלילה\nעכשיו",
		"organ_order_eyebrow": "הסדר משנה את הקרב",
		"organ_choice_title": "איזו מערכת תושמד ראשונה?",
		"organ_choice_body": "כל איבר מפעיל מתקפה חיצונית אחת. בחרו באיום שמשפיע ביותר על המבנה שלכם.",
		"organ_fallback": "איבר",
		"mutation_eyebrow": "הבוס השתנה. עכשיו תורכם.",
		"mutation_choice_title": "בחירת מוטציה",
		"mutation_fallback": "מוטציה",
		"reroll_left": "ערבוב מחדש · נותרו {count}",
		"colossus_collapsed": "הענק קרס",
		"diver_lost": "הצולל אבד",
		"victory": "ניצחון",
		"nest_remembers": "הקן זוכר",
		"victory_body": "הענק שנפל הופך לדלק עבור הקן.",
		"killed_by": "גורם המוות: {cause}",
		"unknown_attack": "מתקפה לא ידועה",
		"result_details": "זמן {time}    איברים {organs}/3    נשמר +{bio}",
		"score_value": "ניקוד {value}",
		"result_loadout": "{boss} · {weapon}",
		"result_organs_destroyed": "הושמדו: {value}",
		"result_mutations": "מוטציות: {value}",
		"result_metrics": "זמן {time} · עומק {depth} · נשמר +{bio}",
		"friend_target_beaten": "יעד החבר הושג",
		"friend_target_missed": "יעד החבר טרם הושג",
		"more_count": "+{count} נוספים",
		"none": "ללא",
		"dive_again": "צלילה נוספת",
		"share_rift": "שיתוף הקרע",
		"return_to_nest": "חזרה לקן",
		"dive_paused": "הצלילה מושהית",
		"pause_body": "הקרב קפוא בבטחה.",
		"resume": "המשך",
		"abandon_to_nest": "נטישה וחזרה לקן",
		"state_intro": "מתקרבים לענק",
		"state_exterior": "קליפה חיצונית · שברו את השריון",
		"state_breach_open": "הפרצה פתוחה · צללו עכשיו",
		"breach_timer": "הפרצה נסגרת בעוד {seconds} שנ׳",
		"breach_lost": "הפרצה נאטמה — שברו שוב את הצלקת",
		"state_organ_select": "בחרו איבר",
		"state_diving_in": "מתקפלים דרך הפצע",
		"state_internal_rooms": "בפנים · הגיעו אל האיבר",
		"state_organ_chamber": "חדר האיבר · השמידו אותו",
		"state_mutation_choice": "בחרו מוטציה",
		"state_diving_out": "החוץ נכתב מחדש",
		"state_core": "ליבה סופית · חסלו את הענק",
		"state_dead": "הצולל אבד",
		"state_victory": "הענק קרס",
		"state_fallback": "צלילה",
		"tutorial_move": "גררו כדי לנוע · הנשק יורה אוטומטית",
		"colossus_fallback": "ענק",
		"internal_depth": "עומק פנימי",
		"keep_moving": "המשיכו לנוע",
		"destroy_organ": "השמידו את {organ}",
		"the_organ": "האיבר",
		"breach_enter": "הפרצה פתוחה — היכנסו אל הענק",
		"all_systems_dead": "כל המערכות הושמדו — מוטטו את הליבה",
		"ability_disabled": "{ability} הושבתה",
		"friend_rift_copied_short": "קרע החברים הועתק · {code}",
		"room_traversal": "מעבר",
		"room_combat": "קרב",
		"room_hazard": "סכנה",
		"organ_scan": "סריקה · {hp} רקמה · {hazard}",
		"synergy": "◆ סינרגיה",
		"synergy_detail": "◆ סינרגיה · {tag}",
		"rare": "נדיר",
		"meta_reward": "יעד הושלם · +{bio} חומר · +{shards} רסיסים",
		"daily_contracts": "חוזים יומיים",
		"achievements": "הישגים",
		"completed": "הושלם",
		"goal_progress": "{value}/{target}",
		"reset_warning": "פעולה זו מוחקת לצמיתות מהמכשיר מטבעות, פתיחות, שיאים, הישגים והתקדמות הדרכה.",
		"reset_confirm": "איפוס לצמיתות",
		"cancel": "ביטול",
		"room_chamber": "חדר איבר",
		"room_entrance": "כניסה",
		"room_room": "חדר",
		"internal_defender": "מגן פנימי",
		"rupture_volley": "מטווח קריעה",
		"hostile_projectile": "קליע עוין",
		"core_collapse": "קריסת ליבה",
		"ability_homing_eye": "עין מתבייתת",
		"ability_gravity_ring": "טבעת כבידה",
		"ability_bone_missiles": "טילי עצם",
		"ability_prism_lances": "רמחי מנסרה",
		"ability_laser_wings": "כנפי לייזר",
		"ability_halo_barrier": "מחסום הילה",
		"ability_suction_waves": "גלי יניקה",
		"ability_chain_lightning": "ברק שרשרת",
		"ability_parasite_swarm": "נחיל טפילים",
		"ability_weapon_copy": "העתקת נשק",
		"ability_echo_dash": "זינוק הד",
		"ability_false_weakpoints": "נקודות תורפה מזויפות"
	}
}

func _ready() -> void:
	SettingsManager.language_changed.connect(_on_language_changed)

func text(key: String, values: Dictionary = {}) -> String:
	var locale := String(SettingsManager.get_value("language","en"))
	var table: Dictionary = STRINGS.get(locale,STRINGS.en)
	var result := String(table.get(key,STRINGS.en.get(key,key)))
	for value_key in values:
		result=result.replace("{%s}"%value_key,str(values[value_key]))
	return result

func content_text(category: String, item_id: String, field: String, fallback: String = "") -> String:
	var locale := String(SettingsManager.get_value("language", "en"))
	if locale != "he":
		return fallback
	var category_table: Dictionary = HebrewContent.CONTENT.get(category, {})
	var item_table: Dictionary = category_table.get(item_id, {})
	return String(item_table.get(field, fallback))

func ability_text(ability_id: String) -> String:
	if ability_id == "basic_rupture":
		return text("rupture_volley")
	var key := "ability_%s" % ability_id
	if STRINGS.en.has(key):
		return text(key)
	return ability_id.replace("_", " ").capitalize()

func hazard_text(hazard_id: String) -> String:
	var fallback := hazard_id.replace("_", " ").capitalize()
	return content_text("hazard", hazard_id, "name", fallback)

func cause_text(cause_id: String) -> String:
	if cause_id.begins_with("ability:"):
		return ability_text(cause_id.trim_prefix("ability:"))
	if cause_id.begins_with("hazard:"):
		return hazard_text(cause_id.trim_prefix("hazard:"))
	match cause_id:
		"internal_defender", "Internal Defender": return text("internal_defender")
		"rupture_volley", "Rupture Volley": return text("rupture_volley")
		"hostile_projectile", "hostile projectile": return text("hostile_projectile")
		"core_collapse", "core collapse": return text("core_collapse")
		"", "unknown_attack", "unknown attack": return text("unknown_attack")
		_: return cause_id

func room_type_text(room_type: String) -> String:
	var key := "room_%s" % room_type
	return text(key) if STRINGS.en.has(key) else room_type.replace("_", " ").capitalize()

func start_alignment() -> HorizontalAlignment:
	return HORIZONTAL_ALIGNMENT_RIGHT if is_rtl() else HORIZONTAL_ALIGNMENT_LEFT

func layout_direction() -> Control.LayoutDirection:
	return Control.LAYOUT_DIRECTION_RTL if is_rtl() else Control.LAYOUT_DIRECTION_LTR

func is_rtl() -> bool:
	return String(SettingsManager.get_value("language","en"))=="he"

func _on_language_changed(locale: String) -> void:
	locale_changed.emit(locale)
